# Generated by Django 5.2.7 on 2026-02-21 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicBranch",
            fields=[
                ("branch_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch_location", models.CharField(max_length=100)),
                ("branch_address", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("suffix", models.CharField(blank=True, max_length=10, null=True)),
                ("patient_address", models.CharField(max_length=300)),
                ("patient_contact_number", models.CharField(max_length=11)),
                ("birthday", models.DateField()),
                ("sex", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("supplier_id", models.AutoField(primary_key=True, serialize=False)),
                ("supplier_name", models.CharField(max_length=150)),
                ("contact_person", models.CharField(max_length=100)),
                ("supplier_contact_number", models.CharField(max_length=11)),
                (
                    "supplier_address",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                ("treatment_id", models.AutoField(primary_key=True, serialize=False)),
                ("treatment_name", models.CharField(max_length=100)),
                ("treatment_type", models.CharField(max_length=30)),
                ("treatment_cost", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("account_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=150)),
                ("account_type", models.CharField(max_length=25)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                ("all_branches", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.clinicbranch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryShipment",
            fields=[
                (
                    "inventory_record_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("received_product_name", models.CharField(max_length=100)),
                ("date_received", models.DateField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.clinicbranch",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesTransaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_date", models.DateField(auto_now_add=True)),
                ("mode_of_payment", models.CharField(max_length=20)),
                (
                    "total_price_of_products",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "total_price_of_treatments",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinic.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_type", models.CharField(max_length=30)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_purchased", models.IntegerField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinic.product",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.salestransaction",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinic.treatment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientVisit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_notes", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.clinicbranch",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinic.patient"
                    ),
                ),
            ],
            options={
                "unique_together": {("patient", "branch")},
            },
        ),
        migrations.CreateModel(
            name="BranchProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_minimum", models.IntegerField(default=0)),
                ("stock_quantity", models.IntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.clinicbranch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinic.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("branch", "product")},
            },
        ),
        migrations.CreateModel(
            name="ReceivedProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_received", models.IntegerField()),
                ("expiration_date", models.DateField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.clinicbranch",
                    ),
                ),
                (
                    "inventory_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.inventoryshipment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinic.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("inventory_record", "product")},
            },
        ),
        migrations.CreateModel(
            name="BranchTreatment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availability_status", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.clinicbranch",
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.treatment",
                    ),
                ),
            ],
            options={
                "unique_together": {("branch", "treatment")},
            },
        ),
        migrations.CreateModel(
            name="TreatmentProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.IntegerField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.clinicbranch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clinic.product"
                    ),
                ),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinic.treatment",
                    ),
                ),
            ],
            options={
                "unique_together": {("branch", "treatment", "product")},
            },
        ),
    ]
