# Generated by Django 5.1.5 on 2026-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_branchproduct_id_alter_branchtreatment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
