# Generated by Django 5.2.7 on 2026-03-16 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_employeeprofile_delete_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicbranch",
            name="branch_address",
        ),
        migrations.AddField(
            model_name="clinicbranch",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clinicbranch",
            name="branch_location",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
