# Generated by Django 5.2.7 on 2026-03-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_remove_clinicbranch_branch_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicbranch",
            name="branch_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
