# Generated by Django 6.0.3 on 2026-03-22 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinicbranch_branch_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryshipment',
            name='date_received',
        ),
        migrations.AlterField(
            model_name='receivedproduct',
            name='inventory_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_products', to='clinic.inventoryshipment'),
        ),
    ]
