# Generated by Django 6.0.3 on 2026-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_remove_clinicbranch_date_added_userlockout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicbranch',
            name='date_added',
        ),
    ]
