# Generated by Django 5.1.5 on 2026-04-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_clinicbranch_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
