# Generated by Django 5.1.5 on 2026-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_alter_patient_middle_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'middle_name', 'birthday'), name='unique_patient_identity'),
        ),
    ]
