# Generated by Django 6.0.3 on 2026-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_patient_unique_patient_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
