# Generated by Django 5.2.7 on 2026-04-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0016_supplier_is_deleted"),
        ("clinic", "0018_clinicbranch_is_deleted"),
    ]

    operations = []
