<<<<<<< HEAD
# Generated by Django 5.2.7 on 2026-04-25 22:01
=======
# Generated by Django 6.0.3 on 2026-04-25 16:24
>>>>>>> 1b694701c59bc7fbddd141d8290b92a6b1482c9f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("clinic", "0019_merge_20260425_2336"),
=======
        ('clinic', '0019_merge_20260425_2336'),
>>>>>>> 1b694701c59bc7fbddd141d8290b92a6b1482c9f
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name="clinicbranch",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="is_deleted",
=======
            model_name='clinicbranch',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='is_deleted',
>>>>>>> 1b694701c59bc7fbddd141d8290b92a6b1482c9f
            field=models.BooleanField(default=False),
        ),
    ]
