# Generated by Django 6.0.3 on 2026-04-25 16:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_merge_20260425_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicbranch',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]