# Generated by Django 5.2.7 on 2026-04-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0020_remove_clinicbranch_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicbranch",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
