# Generated by Django 5.1.5 on 2026-04-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_clinicbranch_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentProduct',
        ),
    ]
