# Generated by Django 6.0.3 on 2026-03-22 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_remove_inventoryshipment_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryshipment',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
