# Generated by Django 5.1.5 on 2026-03-31 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_inventoryshipment_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.clinicbranch'),
        ),
    ]
