# Generated by Django 5.2.7 on 2026-04-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0015_patient_unique_patient_identity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicbranch",
            name="branch_address",
        ),
        migrations.RemoveField(
            model_name="salestransaction",
            name="total_price_of_products",
        ),
    ]
