# Generated by Django 5.2.7 on 2026-04-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0016_remove_clinicbranch_branch_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicbranch",
            name="branch_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="total_price_of_products",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=8, null=True
            ),
        ),
    ]
